import "./globals.css";
import AuthProvider from "@/components/AuthProvider";
import Login from "../components/login";
import styles from "./page.module.css";

import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";

import Button from "@mui/material/Button";
import AppBar from "@mui/material/AppBar";
import Box from "@mui/material/Box";
import Toolbar from "@mui/material/Toolbar";
import ThemeRegistry from "@/components/Theme";


const inter = Inter({ subsets: ["latin"] });




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <body className={inter.className}>
        {/* <Box sx={{ flexGrow: 1 }}>
          <AppBar position="static">
            <Toolbar>
              <Link href="/home">
                <Button color="inherit">HOME</Button>
              </Link>
              <Link href="/dashboard">
                <Button color="inherit">DASHBOARD</Button>
              </Link>
              <Box sx={{ flexGrow: 1 }} />
              <Box sx={{ display: { xs: "none", md: "flex" } }}>
                <Login />
              </Box>
            </Toolbar>
          </AppBar>
        </Box> */}
        <ThemeRegistry theme={theme}>
          <AuthProvider> {children}</AuthProvider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
